### ISSUE TITLE
show build/test status during it's execution

### ISSUE THREAD

**Issue by todoleza** [packit-service/packit-service#204] opened 2019-11-05 12:34 UTC
Now it is not possible to click-through messages reported by Packit to github issue to see whether/where the current pending/running task is being executed.
Best would be to have a link to some pipeline log describing what tasks are being executed, to e.g. see status of a COPR build directly via copr interface.
Having to see the status could help to observe errors in end-user configuration earlier than after the jobs are finished.

**Comment by dhodovsk** [comment] 2019-11-06 11:48
Duplicate of https://github.com/packit-service/packit-service/issues/1

**Closed** 2019-11-06 11:48 UTC
