### ISSUE TITLE
Testing status appears before copr build is finished

### ISSUE THREAD

**Issue by psss** [packit-service/packit-service#279] opened 2019-12-04 15:57 UTC
In the pull request details I see a failed test results even before the corresponding copr build is finished. This is causing confusion. Don't have an example pull request at hand as the results have been later overwritten. Here's the original pull request: https://github.com/psss/tmt/pull/56

**Comment by TomasTomecek** [comment] 2019-12-04 16:22
this is gonna be freakin' hard to debug, since the problem can be in so many places and without a real reproducer (or logs) it's so hard to even start working on this

I blame either our code (and the code which is related to this problem is being rewritten a ton in my pr #257) or fedora-messaging, or GitHub, or universe and black holes

**Comment by TomasTomecek** [comment] 2019-12-04 16:28
okay, this happened twice to me already - so it really seems like a bug in our code

**Comment by TomasTomecek** [comment] 2019-12-04 16:34
checked logs and I think I couldn't find corresponding fedora-messaging event, but the testing part wouldn't get triggered so...

**Comment by jpopelka** [comment] 2019-12-05 12:50
We've changed the related code recently, we'll see more after deploying it.

**Comment by TomasTomecek** [comment] 2020-01-28 16:20
The new code is live, and this should be fixed then. Feel free to reopen if you run into this again.

**Closed by TomasTomecek** 2020-01-28 16:20 UTC
Labels: bug, user-experience
