### ISSUE TITLE
Raise a better exc when packit is run on a project without config

### ISSUE THREAD

**Issue by jpopelka** [packit-service/packit-service#27] opened 2019-05-20 12:07 UTC
Seeing this in `packit-prod` logs:

```
GitHub pull request 11 event for repo packit-service/packit.dev.
ogr_services.py   DEBUG  Authenticating with Github using a Githab app.
config.py         DEBUG  The config file '.packit.yaml' not found on ref '29e7b2b17bf2288ca5c3e5c44fb34c0913453ab8' of the packit-service/packit.dev repository.FileNotFoundError("File '.packit.yaml' on 29e7b2b17bf2288ca5c3e5c44fb34c0913453ab8 not found", UnknownObjectException(404, {'message': 'Not Found', 'documentation_url': 'https://developer.github.com/v3/repos/contents/#get-contents'}))
config.py         DEBUG  The config file '.packit.yml' not found on ref '29e7b2b17bf2288ca5c3e5c44fb34c0913453ab8' of the packit-service/packit.dev repository.FileNotFoundError("File '.packit.yml' on 29e7b2b17bf2288ca5c3e5c44fb34c0913453ab8 not found", UnknownObjectException(404, {'message': 'Not Found', 'documentation_url': 'https://developer.github.com/v3/repos/contents/#get-contents'}))
config.py         DEBUG  The config file '.packit.json' not found on ref '29e7b2b17bf2288ca5c3e5c44fb34c0913453ab8' of the packit-service/packit.dev repository.FileNotFoundError("File '.packit.json' on 29e7b2b17bf2288ca5c3e5c44fb34c0913453ab8 not found", UnknownObjectException(404, {'message': 'Not Found', 'documentation_url': 'https://developer.github.com/v3/repos/contents/#get-contents'}))
config.py         DEBUG  The config file 'packit.yaml' not found on ref '29e7b2b17bf2288ca5c3e5c44fb34c0913453ab8' of the packit-service/packit.dev repository.FileNotFoundError("File 'packit.yaml' on 29e7b2b17bf2288ca5c3e5c44fb34c0913453ab8 not found", UnknownObjectException(404, {'message': 'Not Found', 'documentation_url': 'https://developer.github.com/v3/repos/contents/#get-contents'}))
config.py         DEBUG  The config file 'packit.yml' not found on ref '29e7b2b17bf2288ca5c3e5c44fb34c0913453ab8' of the packit-service/packit.dev repository.FileNotFoundError("File 'packit.yml' on 29e7b2b17bf2288ca5c3e5c44fb34c0913453ab8 not found", UnknownObjectException(404, {'message': 'Not Found', 'documentation_url': 'https://developer.github.com/v3/repos/contents/#get-contents'}))
config.py         DEBUG  The config file 'packit.json' not found on ref '29e7b2b17bf2288ca5c3e5c44fb34c0913453ab8' of the packit-service/packit.dev repository.FileNotFoundError("File 'packit.json' on 29e7b2b17bf2288ca5c3e5c44fb34c0913453ab8 not found", UnknownObjectException(404, {'message': 'Not Found', 'documentation_url': 'https://developer.github.com/v3/repos/contents/#get-contents'}))
ERROR    There was an exception while processing the event.
ERROR    'NoneType' object has no attribute 'upstream_project_url'
Traceback (most recent call last):
  File "/src/packit/service/web_hook.py", line 112, in _give_event_to_steve
    steve.process_message(event)
  File "/src/packit/jobs.py", line 217, in process_message
    response = self.parse_event(event)
  File "/src/packit/jobs.py", line 168, in parse_event
    response = self.get_job_input_from_github_pr(event)
  File "/src/packit/jobs.py", line 118, in get_job_input_from_github_pr
    package_config.upstream_project_url = https_url
AttributeError: 'NoneType' object has no attribute 'upstream_project_url'
```

EDIT: The app should not be installed on all repositories of our organization, only the selected ones, but still, the exception can be nicer.

**Comment by TomasTomecek** [comment] 2019-06-26 08:52
~dupe of #23

**Comment by TomasTomecek** [comment] 2019-08-06 10:43
assigning myself, this pisses me off :D

**Closed** 2019-08-06 11:55 UTC
Labels: bug
